version: "3.7"

services:
  keycloak:
    image: keycloak/keycloak:26.0.2
    command: start-dev
    environment:
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./target/remote-validator-jar-with-dependencies.jar:/opt/keycloak/providers/remote-validator-jar-with-dependencies.jar
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
